### ISSUE TITLE
Store attributes in the database

### ISSUE THREAD

**Issue by acebanenco** [Zybercik00/DataSyncExcel#11]
Currently attributes that can be used for mapping are stored in Java code. 
Application should keep metainfo in database so when new DB changes are added it should be available for mapping.

**Comment by Zybercik00** [comment]
Need to get knowledge about Hibernate inheritance, SuperBuilder, @EqualsAndHashCode(callSuper = true, onlyExplicitlyIncluded = true) and also understand how to get attributes from the database.

**Comment by acebanenco** [comment]
Kindly follow below script: 
- use Joined inheritance strategy
- load initial metadata from json
- reference attribute from mapping
- add JSON schema for attributes and mappings
- move meta entities outside domain package
- add json 2 pojo maven plugin to generate classes from metadata schema
- cleanup entities from builder/constructor annotations
- extend ReferenceAttributeEntity from base AttributeEntity
- move liquibase plugin and resources to app for now
- fix attributes_schema.json format
- define json2pojo plugin in parent, use in init
- add metadata initializer to AppConfig
- specify length for some of varchar columns
- attribute creation has been moved to a factory
- updated attribute schema and entity for qualified, flattened qualifier
- refactored loading metadata, moved to coresponding loaders
- lazy attribute/mapping creation, skip if missing already
- store qualifier value as JsonNode in DB using custom converter
- update qualified attribute schema, make value one of string or value list
- load initial metadata from Json to DB
- load metadata from DB before mapping process
- update nullability for mandatory columns
- add missing attributes and mappings in initial metadata Json
- Exclude parent attributes from entities @tostring
- cascade persist for qualified attributes
- add unique constraints for metadata entities
- generate path automatically for attributes
- add onlyExplicitlyIncluded for every @EqualsAndHashCode
- do not generate DDL by default, use init spring profile to keep generation settings
- rename Excel file to remove trailing space from base name 
- add liquibase master and version 1.0 XML files 
- add @UniqueConstraint to each entity where applicable
- add @ForeignKey to each @JoinColumn
- rename bad column and table names 
- add liquibase dependency to make sure it is triggered on application start
- add unique constraints for PurchasePrice and SalePrice which is based on currency/margin and extraction
- replace JsonBackReference with JsonIgnore

**Comment by Zybercik00** [comment]
I don't understand why in the attributes.json and mappings.json files we only have a few cases (instances) of attribute types or mappings.

**Comment by acebanenco** [comment]
> I don't understand why in the attributes.json and mappings.json files we only have a few cases (instances) of attribute types or mappings.

It wasn't important to have all attributes and mappings to test the concept.
