### ISSUE TITLE
Excel file import

### ISSUE THREAD

**Issue by Zybercik00** [Zybercik00/DataSyncExcel#3]
Import data from sampel excel file
All excel file should have header row
Data should be imported from first sheet 
Data should be added incrementally (update existing rows, add new rows)
[Chemical treatment process .xlsx](https://github.com/Zybercik00/DataSyncExcel/files/12104167/Chemical.treatment.process.xlsx)

**Comment by acebanenco** [comment]
Depends on issue #4
